---
# checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
# https://docs.github.com/en/actions/quickstart
# hhttps://github.com/marketplace/actions/build-and-publish-docker-image-to-github-container-registry
name: "HashiQube DevOps Lab Pipeline"

on: # yamllint disable-line rule:truthy
  push: # yamllint disable-line rule:empty-values

jobs:
  build-and-publish-latest:
    if: ${{ vars.REBUILD_CONTAINER_IMAGE == 'true' }}
    runs-on: ubuntu-latest

    steps:
      # Checking out the repo
      - uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      # https://blog.thesparktree.com/docker-multi-arch-github-actions
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # https://github.com/docker/metadata-action#tags-input
          # tags: ${{ steps.meta.outputs.tags }}
          tags: ghcr.io/${{ github.repository_owner }}/hashiqube:latest # INFO: Hardcoding latest tag
          labels: ${{ steps.meta.outputs.labels }}
